### ISSUE TITLE
Are you open for Salesforce opportunity?

### ISSUE THREAD

**Issue by rick-yang-airwallex** [apexfarm/ApexTriggerHandler#1]
@inksword I am quite interested in your Salesforce solutions. Are you open for Salesforce opportunity?

**Comment by inksword** [comment]
Thanks for liking this library. If any new opportunity, would you mind if discuss it with my personal email (jeff.jianfeng.jin@gmail.com)?

**Comment by rick-yang-airwallex** [comment]
Awesome. Email sent.
