### ISSUE TITLE
Looks good, but all tests fail depending on account validations

### ISSUE THREAD

**Issue by renatoliveira** [apexfarm/ApexTriggerHandler#3]
I just deployed this to a sandbox and all 25 tests fail because of a custom validation rule on the account object.

I know that I'm able to teak the test setup so that the accounts can be inserted, however it would be nice to be able to deploy this without worrying that its tests can fail.

Might make a PR later, I don't know. But I believe that maybe a small disclaimer on the README would be nice for now.

What do you think?

**Comment by inksword** [comment]
The tests are designed in a way to avoid actual DMLs, so it just have the coverage and assertions. If the tests cannot be run in sandbox, the issues must be critical to the library. Could you give me an example of the custom validation rule that preventing the tests success? Or and log detail? Because the tests have had any insert/update statement, it could be something I haven't think of. Thank you for your feedback.

**Comment by renatoliveira** [comment]
>Could you give me an example of the custom validation rule that preventing the tests success?

Think about basically any validation rule that might prevent users from creating accounts. A custom field that cannot be blank, for example (that was my case). With the way the test code is today, if I add the classes to the org and a validation rule like that is in place, then the test setup will fail (and thus all 25 tests will fail as consequence).

As an improvement, the tests probably should not do a DML to test the trigger. Maybe the code on the Props constructor could verify if it is an actual trigger context (`Trigger.isExecuting`) to initialize the props' values. In a test scenario, those values could be assigned by the test (and then no DML would be required to test the multiple different scenarios, since we would be assigning those values by ourselves, without relying on the `Trigger` class in a real trigger context).

**Comment by inksword** [comment]
The tests don’t do any DMLs in its current state. I am a bit confusing about the failure, could it be something else? I will add a validation rule on account.description field and test it later. Also will test around FLS for the fields used in the tests.

**Comment by renatoliveira** [comment]
> The tests don’t do any DMLs in its current state. I am a bit confusing about the failure, could it be something else? I will add a validation rule on account.description field and test it later. Also will test around FLS for the fields used in the tests.

The tests might not do any DMLs, but [the test setup does](https://github.com/apexfarm/ApexTriggerHandler/blob/master/apex-trigger-handler/classes/TriggersTest.cls#L267)! It inserts three account records filling three fields.

In a particular org where I'm using the framework, this was the error I initially got:

    System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Not a valid value for this field!: []
    Class.TriggersTest.makeData: line 267, column 1

It is caused by a validation rule on a custom field.

Of course, I can make a workaround and just add the required fields/data on that test setup, and it will work.

**Comment by inksword** [comment]
All right, thank you for the notice. Good bug and suggestion. Fixing in a day or two.
